# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Procrustes Transform of Rectangular matrix
#' 
#' @param X dense matrix to transform
#' @param target dense matrix that is the target of the transform
#' @param translation boolean; whether positions should be translated
#' @param scale boolean; whether positions should be scaled
#' @return returns a list of four elements: 
#' \enumerate{
#'     \item the transformed matrix \code{Xstar}
#'     \item the rotation matrix \code{R}
#'     \item the translation vector \code{t_vec}
#'     \item the scaling factor \code{sigma}
#' }
#' The transformed matrix \code{Xstar} can be recreated by the equation \code{sigma * X * R} if \code{translation} is \code{FALSE}. If \code{translation} is \code{TRUE}, adding \code{t_vec} to each row of the matrix \code{sigma * X * R} completes the transformation.
#' @export
procrustes <- function(X, target, translation = TRUE, scale = TRUE) {
    .Call(`_igplot_procrustes`, X, target, translation, scale)
}

