#' Extract subset from plot-ready list
#' 
#' @param x list of data.tables to subset (generated by igraph_plot_prep)
#' @param sub_var variables to subset on
#' @param sub_val value to subset on
#' @param keep_edges what edges to keep
subset_plot_df = function(
    x, 
    sub_var, 
    sub_val, 
    keep_edges = c("all", "within", "none")
) {
    
    if (class(x) != "igplotdat")
        stop("`x` has to be a `igplotdat` object")
    
    keep = match.arg(keep_edges, several.ok = FALSE)
    
    stopifnot(
        length(sub_var) == 1L,
        is.character(sub_var),
        all(sub_val %in% unique(sub_var)),
        "name" %in% names(x$vertices),
        all(c("name1", "name2") %in% names(x$edges))
    )
    
    # subset vertices
    x$vertices = x$vertices[get(sub_var) %in% sub_val]
    
    # update edges
    if (keep == "none") {
        
        x$edges = x$edges[0L]
        
    } else if (keep == "all") {
        
        # get names
        v_names = x$vertices$name
        el = x$edges[
            (name1 %in% v_names) | (name2 %in% v_names)
        ]
        
        x$edges = el
        
    } else {
        
        # get names
        v_names = x$vertices$name
        el = ve_list$e_dat[
            (name1 %in% v_names) & (name2 %in% v_names)
        ]
        x$edges = el
        # c_names = data.table(
        #     # all not-selected vertices
        #     en = c(
        #         el[!(name1 %in% v_names), name1],
        #         el[!(name2 %in% v_names), name2]
        #     )
        # )[
        #     # count number
        #     , N := .N, by = "en"
        # ][
        #     # keep only nodes that are connected to at least two of selected ones
        #     N > 1L
        # ]
        # 
        # # select only edges that connect nodes among selected nodes
        # new_v_names = c(v_names, c_names$en)
        # ve_list$e_dat = el[
        #     (name1 %in% new_v_names) & (name2 %in% new_v_names)
        # ]
        
    }
    
    return(x)
    
}