#' Extract subset from plot-ready list
#' 
#' @param ve_list list of data.tables to subset (generated by igraph_plot_prep)
#' @param sub_var variables to subset on
#' @param sub_val value to subset on
#' @param keep_edges what edges to keep
subset_plot_df = function(
    ve_list, 
    sub_var, 
    sub_val, 
    keep_edges = c("all", "connected", "none")
) {
    
    keep = match.arg(keep_edges, several.ok = FALSE)
    
    stopifnot(
        length(sub_var) == 1L,
        length(ve_list) == 2L,
        is.character(sub_var),
        all(c("v_dat", "e_dat") %in% names(ve_list)),
        "name" %in% names(ve_list$v_dat),
        all(c("name1", "name2") %in% names(ve_list$e_dat))
    )
    
    # update v_dat
    ve_list$v_dat = ve_list$v_dat[get(sub_var) %in% sub_val]
    
    # update e_dat
    if (keep == "none") {
        
        ve_list$e_dat = ve_list$e_dat[0]
        
    } else if (keep == "all") {
        
        # get names
        v_names = ve_list$v_dat$name
        el = ve_list$e_dat[
            (name1 %in% v_names) | (name2 %in% v_names)
        ]
        
        ve_list$e_dat = el
        
    } else {
        
        # get names
        v_names = ve_list$v_dat$name
        el = ve_list$e_dat[
            (name1 %in% v_names) | (name2 %in% v_names)
        ]
        
        c_names = data.table(
            # all not-selected vertices
            en = c(
                el[!(name1 %in% v_names), name1],
                el[!(name2 %in% v_names), name2]
            )
        )[
            # count number
            , N := .N, by = "en"
        ][
            # keep only nodes that are connected to at least two of selected ones
            N > 1L
        ]
        
        # select only edges that connect nodes among selected nodes
        new_v_names = c(v_names, c_names$en)
        ve_list$e_dat = el[
            (name1 %in% new_v_names) & (name2 %in% new_v_names)
        ]
        
    }
    
    return(ve_list)
    
}